//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConexionDatos
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class libro
    {
        public int id { get; set; }

        [Required]
        [DisplayName("Título")]
        public string titulo { get; set; }

        [Required]
        [DisplayName("Año")]
        public short anio { get; set; }

        [Required]
        [DisplayName("Genero")]
        public string genero { get; set; }

        [Required]
        [DisplayName("Número de páginas")]
        public short num_paginas { get; set; }


        [Required]
        [DisplayName("Autor")]
        public string nombre_autor { get; set; }

        public int autor_id { get; set; }
    
        public virtual autor autor { get; set; }
    }
}
